/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package de.beiertu.kafka.protobuf.example

import de.beiertu.kafka.protobuf.example.kafka.DefaultEventProducer
import de.beiertu.protobuf.Person

class App {
    companion object {
        private val producer = DefaultEventProducer()

        @JvmStatic
        fun main(args: Array<String>) {
            val message = Person.newBuilder()
                .setName("Tung")
                .setAge(30)
                .setGender(Person.Gender.MALE)
                .build()

            producer.publish(message)?.let {
                println("published event on topic=${it.topic()}, partition=${it.partition()}, offset=${it.offset()}")
            } ?: println("failed to publish event")
        }
    }
}
